# Generated by Django 4.2.7 on 2023-11-09 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creador', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTopVideos.categoria')),
                ('plataformas', models.ManyToManyField(to='appTopVideos.plataforma')),
            ],
        ),
        migrations.AddField(
            model_name='plataforma',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='appTopVideos.video'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='appTopVideos.video'),
        ),
    ]
